kind: namespace
metadata:
  name: frontend-2024-02
  labels:
    folder.kubevirt.io/name: dev   # works in OCP as namesapces are protected there, user no access
spec: {}
---
kind: namespace
metadata:
  name: frontend-2024-01
  labels:
    folder.kubevirt.io/name: stage   # works in OCP as namesapces are protected there, user no access
spec: {}
---
apiVersion: folders.kubevirt.io/v1alpha1
kind: Folder
metadata:
  name: central-it
  description: Folder for central IT
spec:
  roleBinding:
    subjects:
    - kind: Group
      name: it-staff
      roleRef:
        kind: Role
        name: admin
---
apiVersion: folders.kubevirt.io/v1alpha1
kind: Folder
metadata:
  name: dev
  description: Folder to grant developers privileges on VMs for development
spec:
  parentFolderName: central-it
  roleBinding:
    subjects:
    - kind: Group
      name: dev
      roleRef:
        kind: Role
        name: vm-ops  # start stop vnc console only
  secrets:
    - secretRef:
        namespace: central-it-shared-secrets
        name: dev-subscription-key
---
apiVersion: folders.kubevirt.io/v1alpha1
kind: Folder
metadata:
  name: quarantine
  description: Folders isolated from network for further investigation
spec:
  parentFolderName: central-it
  networkPolicies:
    - # metadata.name can be auto generated
      name: deny-all
      template:
        spec:
          # namespace selector will be infered from folder
          podSelector: {}
          policyTypes:
            - Egress
            - Ingress
